### PR TITLE
Move log file to a standard path

### PR DESCRIPTION
**Pull request by cvuchener**
New default location are:
 - Windows: %APPDATA%/Local/Dwarf Therapist/dwarftherapist.log
 - macOS: ~/Library/Logs/io.github.dwarf-therapist/dwarftherapist.log
 - Linux: no log file
Portable/developer modes stores the log in the application directory.

Log path can be overriden using the "--log=<path>" option.

### CODE REVIEW

**Comment by feelotraveller** [comment]
Is there a reason not to save the log file on linux?

You will know better than me but barring other suggestions how about
~/.local/share/dwarftherapist/
since that location already exists for memory layouts, and has the advantage of keeping thing together?

**Comment by cvuchener** [comment]
Because it used to work that way and there is no standard location for desktop application to store the log (I've read about some applications using XDG_CACHE_HOME ~/.cache for that purpose). Outputting to the console seems the best default. Gnome-shell does store the output from desktop application launched through the shell in the journal (`journalctl --user SYSLOG_IDENTIFIER=dwarftherapist.desktop`). But I don't know if it works with other desktops.

It's macOS I am not sure about. It used to be the same as Windows (log/run.log in the working directory), and, I guess, it has the same issue: you don't know if the working directory is writable. I found a Logs directory in the home directory, it should fit.

I thought about using the writable data location for all platforms but it is not its purpose. Although you are right: it would make it easier to find the log.

**Comment by cvuchener** [comment]
Added XDG_CACHE_HOME/dwarftherapist/log for Linux, and it should log to both stderr and files now. Added log rotation so you can get logs from a few previous sessions too.

I am hesitating about how to make it easier to find them: adding a menu item to open the log directory or moving them to the data directory.

**Comment by cvuchener** [comment]
DT being restarted as root on macOS is messing with the log rotation and permissions.

**Comment by feelotraveller** [comment]
Nice. XDG_CACHE_HOME/dwarftherapist/log is better.

Having a menu item to open the log directory will be useful for DT users no matter their level. :)

**Pull request merged**
