### PR TITLE
Add new thoughts for DF 0.47.05

### PR DESCRIPTION
**Pull request by cvuchener**

### CODE REVIEW

**Comment by cvuchener** [comment]
@lethosor Why are you referencing this PR? Is the "Tactician" name something new in 0.47.05?

**Comment by lethosor** [comment]
Oops, I meant to reference #234. I saw you added some new skills there, and I checked to see whether they were new in 0.47.05. They aren't new ("Tactician" dates back to 2011, possibly earlier) but it had a noun form in df-structures that was inconsistent with the rest. I fixed that, and referenced the PR where I saw that change (or I meant to, at least).

**Comment by cvuchener** [comment]
For the new thoughts https://github.com/DFHack/df-structures/issues/419 would be a better source, since it has both messages. The original bug report is on the forum: http://www.bay12forums.com/smf/index.php?topic=168411.msg8242571#msg8242571

As for #234 it does not add new skills, it adds new columns in one of the default grid views. Military Tactics has been present in DT for years. Intrigue was added last year (c61b5e78b18cf3174d0c7297cec92af76496a1d6). The PR is related to http://www.bay12forums.com/smf/index.php?topic=168411.msg8238255#msg8238255 (and other older requests).

**Comment by lethosor** [comment]
Ok, cool, I saw the DT PRs more recently. I'll look at the issue you opened again.

**Pull request merged**
