### PR TITLE
Allow customize skills ui in tooltip

### PR DESCRIPTION
**Pull request by RusTit**
Related to #97 
This is draft version, it work, but can be improved.

### CODE REVIEW

**Comment by cvuchener** [comment]
Looks good. What improvement are thinking about?

**Comment by RusTit** [comment]
Hm... I'm thinking about HUGE refactoring this project. dwarf.cpp - 119 720 bytes. This tool is awesome, I can't play df without it, but supporting for this code is difficult (IMHO).
MiniBug = The settings are applied only after the table is manually updated. We should add a reload of the table when you click OK.

**Comment by RusTit** [comment]
When I dealt with the code for the last time, I did not like the very long creating of the grid.
Among other things, I would suggest creating a tooltip at the time you point to the dwarf row (after once created it can be cached), this would noticeably speed up. But it was a bit difficult for me at that moment.
I also read on the forums the idea of getting data of the dwarves from Dfhack
We can work on proxy so that in the future can be possible.

**Comment by cvuchener** [comment]
I meant about this PR being a "draft".

> MiniBug = The settings are applied only after the table is manually updated. We should add a reload of the table when you click OK.

Yes, you often need to "read dwarves" before everything is applied. It is nothing new.

> Hm... I'm thinking about HUGE refactoring this project. dwarf.cpp - 119 720 bytes. This tool is awesome, I can't play df without it, but supporting for this code is difficult (IMHO).

DT has a lot of history, it comes from a time when DF internal was not well known, and I believe a previous dev was not very good with C++ (argument passing and memory management are bad in a lot of places).

> I also read on the forums the idea of getting data of the dwarves from Dfhack
> We can work on proxy so that in the future can be possible.

The whole data model would have to be redone. I personally think it would be best to just write a DT2 from scratch but I don't have the courage. I tried a quick and dirty DFHack backend but using a network round-trip every time DT reads an integer is really too slow.

**Comment by RusTit** [comment]
Oh... I misunderstood. =) 
> I meant about this PR being a "draft".

Please check my English in ui (statusTip, whatsThis, text).
If the text are written incorrectly, write your own version.
And in the rest, like everything is fine (for me).
>Yes, you often need to "read dwarves" before everything is applied. It is nothing new.

May still add an update, after clicking Ok?
> The whole data model would have to be redone. I personally think it would be best to just write a DT2 from scratch but I don't have the courage.

Same for me and my cpp even worse (than prev author).
> I tried a quick and dirty DFHack backend but using a network round-trip every time DT reads an integer is really too slow.

And tell me more about this. (I know nothing). There it is necessary to receive each parameter separately? There is no way to get structures (ie serialized objects - it's kind of faster?)?

**Comment by cvuchener** [comment]
> Please check my English in ui (statusTip, whatsThis, text).
If the text are written incorrectly, write your own version.
And in the rest, like everything is fine (for me).

You should have said so. I thought I should expect more commits. I am not a native english speaker either, but I'll see what I can do.

> And tell me more about this. (I know nothing). There it is necessary to receive each parameter separately? There is no way to get structures (ie serialized objects - it's kind of faster?)?

As I've said it was quick and dirty. I simply reimplemented read_raw/write_raw/read_string/write_string using DFHack remote protocol and a simple plugin that catches segfaults when an invalid address is used. Grouping memory accesses is possible and recommended but it would require a lot of changes. Furthermore, a proper DFHack backend should not use addresses, objects are referenced with IDs. And that means even more radical changes. If you want to discuss more about this subject, we should find a better place (forum, emails, ...) than an unrelated PR.

**Comment by RusTit** [comment]
> You should have said so. I thought I should expect more commits.
My mistake While creating the PR, I meant everything is ready, but there may be correction (rename the variables for example, minor).

And since they were not, then it only remains to check the spelling.
> If you want to discuss more about this subject, we should find a better place (forum, emails, ...) than an unrelated PR.

At least it is interesting to me, I would look api, and your raw code. We can chat as you like,  forum is better, someone else can to join the discussion. Also good option - discord. Right now I will not be able to code anything, but in three weeks I will be freer, and now I would read the docks, examples.

**Comment by feelotraveller** [comment]
I like it.  :smile_cat: 

An option to limit the number of displayed skills was a good suggestion, perhaps you could pursue sometime?

I think it would be better to have the checkboxes labelled:
>Show skill level
Show skill experience
Use color highlighting for skills

(Not so sure about the last.)
I am a native english speaker, though that means little.

**Comment by RusTit** [comment]
@feelotraveller I updated the files according to your sample, look at the rest of the text (statusTip, whatsThis).

**Comment by RusTit** [comment]
> An option to limit the number of displayed skills was a good suggestion, perhaps you could pursue sometime?

Maybe. @cvuchener What do you think about that?

**Comment by cvuchener** [comment]
There are already two ways of reducing the number of displayed skills: minimum skill level and "include social skills" are  Adding a third "only show top n skills" feels unnecessary.

**Comment by cvuchener** [comment]
Comparing with the style of other status-tips:
 - add a comma after "When checked".
 - add "the" in "in *the* tooltip".

Color-highlighting tip could be more precise. "When checked, highlights rusted skills in the tooltip."

**Comment by RusTit** [comment]
@cvuchener updated, please check

**Comment by cvuchener** [comment]
If there is no more remarks, I am going to merge this.

**Comment by RusTit** [comment]
You can merge it any time, I have no plans for new commits.

**Pull request merged**
