### PR TITLE
Add memory layouts for 0.44.08-0.44.09

### PR DESCRIPTION
**Pull request by cvuchener**

### CODE REVIEW

**Comment by cvuchener** [comment]
Which platform? I've just tested linux 64 bits, and it connects.

**Comment by filalex77** [comment]
Also Linux x64. Just got 0.44.09 from Bay12 website, doesn't connect. Works fine with 0.44.04.

**Comment by cvuchener** [comment]
Check that your file is not corrupted or truncated. You can also check which memory layout is used by looking in the log for a line like this:

    2018-Apr-02 12:52:21.040 INFO	core	Detected Dwarf Fortress version "v0.44.09 linux64" using MemoryLayout from "/home/clement/projects/Dwarf-Therapist/share/memory_layouts/linux/v0.44.09_linux64.ini" [/home/clement/projects/Dwarf-Therapist/src/dfinstance.cpp:1091] (set_memory_layout)

**Comment by filalex77** [comment]
Hm, strange. It says "permission denied". I already ran setcap first time, and it worked for 0.44.04. Reran the command, works now.

**Pull request merged**
