### PR TITLE
Improve labor tooltip

### PR DESCRIPTION
**Pull request by RusTit**
I took your code as the basis, compared it to my old one.
The code matched completely.
Ref to #94

### CODE REVIEW

**Comment by cvuchener** [comment]
On the coding style: don't use uppercase in variable name, prefer using `first_column` or something in that style.

You left the emotions in the first column. IThey are big paragraphs, they should be in the second column.

I don't like the way the skill lines are broken. Either the first column should be wider, or the line break should be forced before the experience part. Or the experience details may be too much for a tool-tip, and they could be hidden.

infobulle_012
infobulle_014
infobulle_011
infobulle_013
What do you think?


I did not check the less common paragraphs like health info.

**Comment by RusTit** [comment]
> On the coding style: don't use uppercase in variable name, prefer using first_column or something in that style.

Done.
>You left the emotions in the first column. IThey are big paragraphs, they should be in the second column.

Done.
> I don't like the way the skill lines are broken. Either the first column should be wider, or the line break should be forced before the experience part. Or the experience details may be too much for a tool-tip, and they could be hidden.

I like the last option most of all.
I do not think that you need to remove the skills completely
But percentages (usually) are not so useful as to add them to the hint.

P.S.
I have a problem with debugging.
1. I compiled the project with support of Qt 5.10, added the folder "data", but the program cannot connect to the df. I'm trying to understand why.
2. Because I opened the project, as Cmake-project, I cannot use breakpoints.
I have not done this for a very long time, so I'm sorry, I forgot a lot.

**Comment by RusTit** [comment]
I'll try to play tomorrow (I do not have created worlds yet) to see how the other blocks will look like (health, etc.).

**Comment by cvuchener** [comment]
Thanks.

For Windows 64 bits Qt builds, you can use the official ones for MSVC2015/2017 or [MSYS2](https://www.msys2.org/) if you prefer GNU tools.

**Comment by feelotraveller** [comment]
Please don't remove the skill xp's from the tooltips.  They are useful when tracking skill acquistion and particularly with militiary training.  (The percentage counts are redundant though.)

**Comment by RusTit** [comment]
>For Windows 64 bits Qt builds, you can use the official ones for MSVC2015/2017 or MSYS2 if you prefer GNU tools.

That's exactly what I did.
It took a lot of time to re-download and install the required packages, but now I'm compiling under msvc2017 x64

> Please don't remove the skill xp's from the tooltips. They are useful when tracking skill acquistion and particularly with militiary training. (The percentage counts are redundant though.)

If the experience is not removed, I do not know how to make a tooltip compact (option in which the exp on a new line):

I have the suggestion to limit the maximum number of skills in the tooltip

**Comment by cvuchener** [comment]
> Please don't remove the skill xp's from the tooltips. They are useful when tracking skill acquistion and particularly with militiary training. (The percentage counts are redundant though.)

Do you really need it in the general dwarf tool-tip? They would still be in the labor/skill columns tool-tips and the dwarf details widget (with nice progress bars).

**Comment by feelotraveller** [comment]
> Do you really need it in the general dwarf tool-tip?

Need is a strong term.  But in terms of workflow it is _very_ useful to be able to access the information from the tooltips, particularly in the case of activities which lead to multi-skill acquistion, for example military training.  Using the labor/skill columns it would be labourious to check half a dozen plus places for a single dwarf let alone one or several squads worth.  The dwarf details tab is better but requires clicking on each dwarf rather than just rolling over them.

Honestly if the xp disappears from the tooltips I will come nagging to find out how to build a version with the old tooltip.  And although many users will not need this functionality there are others who test these sorts of things who will either bemoan the loss, or wish for the feature in the future.

**Comment by RusTit** [comment]
Meanwhile, as promised screenshots block "health."




Maybe it's also a table to arrange the skills? Those. a separate table after the first with three (then you can add the ability to customize, in the idea of the comment above) with columns.

**Comment by cvuchener** [comment]
> The dwarf details tab is better but requires clicking on each dwarf rather than just rolling over them.

I agree clicking is not the best way to check a series of dwarves. Keyboard arrows don't move the selection like other tree views. There should be keyboard shortcuts for navigating the unit list but that is another issue.

>Or expand columns in first table to show skills:
>
>| Data1 | Data2 |  Skills |  |  |
>|-------|-------|:-------:|--------------|------|
>|  |  |  Level |  Description |  Exp |
>|  |  |  |  |  |
>|  |  |  |  |  |

I fear that would be wide.

> A separate table after the first 

and that would be to high.

I am fine with either the wider first column or removing the experience info.

But I don't use this tool tip much, I personally prefer the dwarf details dock, so it is hard for me to decide. Everyone will want to add their favorite info but there is no room for everything. I would be more comfortable if there was a clear policy about what should be in the tool tip and what should not.
Or, alternatively, go the full customization way and let the user provides a html template (so it is not my problem any more and the user has to do all the work).

---

On a more technical note, I would prefer to not have commits that only exists to fix a previous change in the same PR (like b26793d1c4ddaf66979842dade7a184041f183a5), so when I merge it looks like you had the perfect idea from the start. 1 commit = 1 feature/fix (1 commit for using columns, and optionally 1 commit for changing the skill description). If finally skill experience is kept, don't revert 14b9e37da0046c33ce0c67e62cae0402b031584f with another commit, just delete it.

It is not a big issue I can do it myself if you don't how to edit history. You can wait until everything is ready before cleaning the commits depending on how you prefer to work.

**Comment by RusTit** [comment]
If I understood correctly, done

**Comment by cvuchener** [comment]
After reflection, most of the options in the "Tooltips" tab, actually modify only the dwarf tooltip. There is already a full page of check boxes for configuring this tooltip, a few more won't hurt. They would control the parameters for Skill::to_string same as the health info options for UnitHealth::get_*_summary. @RusTit are you okay with doing that?

**Comment by RusTit** [comment]
Why not. I could try, but tomorrow. It must be separate PR? I'll see the code later.

**Comment by cvuchener** [comment]
> Why not. I could try, but tomorrow. It must be separate PR? I'll see the code later.

If you doing that in another PR, I think this one is ready for merge.

> If I understood correctly, done

You forgot about b26793d1c4ddaf66979842dade7a184041f183a5. Use interactive rebase and mark the commit as `fixup`.

**Comment by RusTit** [comment]
Please take a look.

**Pull request merged**
