### PR TITLE
ft-tooltip

### PR DESCRIPTION
**Pull request by feelotraveller**
Cleaned up dwarf tooltip (html code ugly but should work)
Replaced highest moodable skill with artifact when created

### CODE REVIEW

**Comment by cvuchener** [comment]
I did not test it yet but I have some remarks after reading the patch.

 - Be careful to use the same indentation style: 4 spaces, no tab.
 - I would prefer XHTML style `<br />` instead of old HTML `<br>`.
 - The way you moved the "Creator of" string make it depend on the "tooltip_show_mood" option instead of "tooltip_show_artifact".
 - You need to write a commit message explaining what the patch do: a short one-line title and a more detailed description if needed.

Why add extra line breaks, are they necessary? How does it compare to using block tags like `<p>` or `<div>`? I was thinking about removing the `<br/>` when joining and instead using `<div>` or `<section>` blocks around every section and tweaking the margins from an external style sheet.

**Comment by cvuchener** [comment]
Have a look at this patch https://github.com/cvuchener/Dwarf-Therapist/commit/378a3298bc04680ef3be7c124075857f20d17949

It makes the space between the sections thinner (but also put space between the "Caste", "Age", "Size", ... lines so it is not perfect).

**Comment by feelotraveller** [comment]
Did not figure out quite why but it was the block sections causing the extra spaces despite the margin:0px commands.  I did not try <div>.  Block sections are not used for styling here and I saw no need of them (beyond those for lists and perhaps title) nor for an external stylesheet.  Decided to manually insert linebreaks and it worked (at least on my machine).  Is there good reason not to do it this way?

Your other comments are spot on and welcome.  I will revise.

**Comment by cvuchener** [comment]
I am still unsure about the reason for the extra space. I dumped the generated html and looked at it in my web browser but it does not look the same. It looks like Qt add an extra empty line when there is a line break before a block element: `<br /><div>block</div>` (a Qt bug?).

The advantage of using block elements with margins over line breaks is that you can finely tune the space between the paragraphs. With line breaks the space is always exactly one line height (or zero, or two, ...). Also the behavior of `<br />` seems harder to predict.

**Comment by cvuchener** [comment]
In #14, I have made some changes around "Highest Moodable Skill", that will surely create a conflict with your patch when I merge. Just to warn you.

About this section, I have second thoughts about moving the "creator of" one. Isn't hiding this part when a dwarf already had a mood enough? (adding ` && !had_mood()` in the condition). It will still save space. The "creator of" line don't take much space at its current position.

**Comment by cvuchener** [comment]
current / with div / yours
  

(ignore the "ID" line, it is only displayed in debug builds)

**Comment by feelotraveller** [comment]
Yes, I agree with leaving the "creator" line where it is and just suppressing the highest moodable skill by "had mood".  And I also agree with the div method it works better. So it looks like you've done all the work and we can just ditch my commit?  (Actually you'll probably have to help me understand how to do that - see below.)  Otherwise I will redo sometime after skill_names merges with master.  I've got a couple of other things I want to do to - had thought I'd be well through all of them by now...
-----------
Read the following at your own risk :) I needed to vent a bit, and probably take a good break.  But friendly suggestions would be welcome.

I've been having ridiculous amounts of trouble coming to terms with git - definitely not helped by not being able to access 'help.github' addresses (don't ask because I don't know - specific to those pages only).  If I was not so determined to be able to contribute (on the content side mainly) in the future I would have rage quit/nuked from orbit several times now.  Every step which should take a couple of minutes ends up being hours and sometimes drags into days still unresolved.  For example how do I sync my repository to the master branch, and my local to my repository.  Or push an edit to this commit.  I've several times spent hours and am just frustrated.  Can't push because different commits, can't fetch because upstream is not a git repository, can't merge because conflicts, can't ... do anything. :(

Honestly is there somewhere that explains it like I am 5 because I think I need it.

**Comment by cvuchener** [comment]
Okay, I will make the changes myself. I am closing this PR.

If you want to learn git, learn git, don't bother with github specifics. Sorry, I don't have a beginner guide to recommend. Once you know the basics, the man pages are quite good.

For managing multiple repos, I create several remotes (man git remote). Currently I have

```
$ git remote -v
feelotraveller	https://github.com/feelotraveller/Dwarf-Therapist.git (fetch)
feelotraveller	https://github.com/feelotraveller/Dwarf-Therapist.git (push)
origin	git@github.com:cvuchener/Dwarf-Therapist.git (fetch)
origin	git@github.com:cvuchener/Dwarf-Therapist.git (push)
upstream	git@github.com:Dwarf-Therapist/Dwarf-Therapist.git (fetch)
upstream	git@github.com:Dwarf-Therapist/Dwarf-Therapist.git (push)
```

Use `git fetch` for fetching remote data, then you can use the branches from the remotes (`git pull` is fetch and merge combined).

So, for rebasing your branch on the new upstream master, after adding the "upstream" remote, you would use from your dev branch `git fetch upstream` and then `git rebase upstream/master` (and follow git instructions if a conflict happens).

When editing your commit history (with `git commit --amend`, `git rebase`, `git reset`, ...), you may have conflicts when trying to push your changes, use `git push --force` and it will overwrites the remote branch. Don't force push on branches that may be used by others, but it is okay if you are working alone on a branch. Feel free to edit commits in pull requests, I prefer to have a nice commit log when merging than to have each change you made to the pull request in the git log (don't add "fix indentation from previous commit" commits, amend the previous commit). Comment the pull request if needed to notify the changes (e.g. "I made the requested changes").

But don't be afraid of not knowing everything, I can make the edits myself if you don't know how (squashing commits or small edits).

**Pull request closed without merging**
