### PR TITLE
Add detailed commitment for sexual orientation

### PR DESCRIPTION
**Pull request by cvuchener**
- Use gender icons with background for commitment level
 - Add Likes/Will marry text in gender/orientation description
 - Add same_sex_commitment/other_sex_commitment accessors for scripts
 - Keep simple orientation for animals (no background, no extra description)

### CODE REVIEW

**Comment by feelotraveller** [comment]
The icons look fine to me.

I couldn't find a sort by gender option.  Thought you posted an image of it on Bay12.  Have I just missed it?  I certainly remember demand for sorting by sex in the past - some players wishing to keep females out of their military (babies).

There will be a demand for showing simplified (sex only) icons.  Particularly since some players wish not to 'cheat'.  Grid options, show simplified gender icons/show advanced gender icons.

**Comment by cvuchener** [comment]
I think I will replace the "Show Gender Icons" check box with a drop down menu: None/Sex only/Orientation.

**Comment by cvuchener** [comment]
The group option is called "Gender & Orientation". For very specific needs of filtering, there are scripts.

**Comment by feelotraveller** [comment]
Drop down menu 👍  Found the group option.

A semi-bug report, not sure how important.  When the orientation flags are changed by DFHack to be a non-standard set (e.g. likes males, will marry males) DT will crash on read.

```
ERROR	core	Invalid interest in suffix [/hdd/down/temp/Dwarf-Therapist-sex-icons/src/dwarf.cpp:456] (sex_interest_icon_suffix)
Segmentation fault
```

**Comment by cvuchener** [comment]
The error message is expected, not the crash.

**Comment by cvuchener** [comment]
I fixed the crash and changed the groups.

The "Sex" option groups by sex only (Female/Male/Unknown). The "Sex Orientation" option group by general sexual orientation (sex + simple orientation (asexual/hetero/homo/bi)). "Sexual Orientation" sorts but does not group by Likes/Marry.

I still have to add the "show nothing/sex only/detailed orientation" option. The current checkbox only changes the display of the icon in the grid view. The Dwarf Detail window always shows the icon. What should I do with the dwarf details when "show nothing" is selected? Or should I use two different settings: "show icon in grid view" and "show detailed sexual orientation"?

**Comment by feelotraveller** [comment]
The possibility to show nothing on the grid view while showing either sex or detailed icons on the dwarf details would make the two setting approach superior, I think.

**Comment by cvuchener** [comment]
done

**Pull request merged**
