### PR TITLE
Add memory layouts for 0.47.01

### PR DESCRIPTION
**Pull request by cvuchener**

### CODE REVIEW

**Comment by woj1993** [comment]
I have problem that every dwarf is seen as visitor so I can't commit any changes is this normal? Animals works correctly.

**Comment by clinodev** [comment]
Interesting, I just assumed these were preliminary when it consistently failed to "Not Responding" at "Loading Units" of 31-37%, for the same fort on the same tick, mind you.

https://imgur.com/sGeyZJ3

**Comment by cvuchener** [comment]
> I have problem that every dwarf is seen as visitor so I can't commit any changes is this normal?

I saw that too (on linux) and a lot of other errors. It is still early and df-structures has not been updated much yet. I only merged Quietust patches (https://github.com/DFHack/df-structures/pull/340).

**Comment by cvuchener** [comment]
It's getting better. I've only seen material names errors, but I did not test much.

**Comment by cvuchener** [comment]
The last update should item materials (on all platform except win64 where it was already working) and historical figures.

**Comment by woj1993** [comment]
I can confirm that win64 is pretty stable. I was playing yesterday for 8 hours and hasn't found any errors.

**Comment by BigSnicker** [comment]
So I took a shot at building this branch, despite being pretty unfamiliar with cmake, and failed pretty miserably (i.e. the Linux version couldn't detect the active DF process and the Win64 version repeatedly gave me "could not find any instance of Visual Studio").

So any idea when this will be released as compiled releases that support 47.01?

**Comment by woj1993** [comment]
@BigSnicker What is your system?

**Comment by BigSnicker** [comment]
Excellent, I'll give it a shot.  Primary system is boring ol' Windows 10/64bit x86 and backup is the same architecture on Ubuntu.

Looking forward to it!  Thanks for all your work, guys.

**Comment by bwach** [comment]
@cvuchener amazing work, thank You! May forgotten beasts bring much "fun" to your forts whenever you expect it the least!

As for feedback, I had an issue
- filter was set to "migration wave"
- migrants were identified as "non citizens" until I re-read 

Is it due to memory mapping or that's how it should be now?

**Comment by cvuchener** [comment]
> So any idea when this will be released as compiled releases that support 47.01?

There was no code changed since last release, you can simply add the new memory layouts to your current installation. There will be a new release when the work on the memory layout is finished.

**Comment by cvuchener** [comment]
> As for feedback, I had an issue
>
>   - filter was set to "migration wave"
>   - migrants were identified as "non citizens" until I re-read
>
> Is it due to memory mapping or that's how it should be now?

That's not normal. I don't know how this could happen. I can't even find where this string comes from (was it really "citizen" or another word?). But I don't think this is a memory layout issue.

**Pull request merged**
