### PR TITLE
Needs

### PR DESCRIPTION
**Pull request by cvuchener**
- [x] read focus and needs
 - [x] display focus paragraph in dwarf tool-tip
 - [x] documentation for script editor
 - [x] colors in descriptions
 - [x] need columns
 - [x] focus column
 - [x] default need grid view
 - [x] add new columns in grid view editor

### CODE REVIEW

**Comment by cvuchener** [comment]
It is hard to get colors to work with different palettes. I am not sure how best set the green/dark green and yellow/dark yellow colors so they are distinct yet both readable. And the (dark) yellow is not as highlighted as it should be on light yellow background.
light_tooltip
dark_tooltip

**Comment by cvuchener** [comment]
Or I could not use the game colors. DT is not limited to the 16 colors palette. So green/dark green/dark yellow/yellow/red could be replaced with blueish green/yellowish green/yellow/orange/red.
light tooltip
dark tooltip

There is still the yellow on yellow issue.

**Comment by cvuchener** [comment]
Color test with Windows:
focus_tooltip

**Comment by cvuchener** [comment]
Just arrived migrants have current_focus and undistracted_focus set to 0. This causes divisions by zero that should be fixed.

IIRC after embark they are set to 1. They looks like cached computation. Maybe I should ignore them and just recompute them in DT.

**Comment by cvuchener** [comment]
Rebased on v40.1.1 and added 0.44.12 offsets.

**Comment by cvuchener** [comment]
Added needs dock widget for overview and filter (similar to though/preference/equipment dock widgets).

**Comment by cvuchener** [comment]
I'm experimenting with using colored bars in the need widget, but it is hard to get the colors right.
needs_bar_light
needs_bar_dark

**Comment by feelotraveller** [comment]
My **personal** view on the colours is that the text colours look good but that the cell colours would be better if they were somewhat paler (more pastel like).

Would it be possible to make the colours user-customisable in a similar fashion to the gridviews?  Just a suggestion since at least the colour picker backend already exists.

**Comment by cvuchener** [comment]
I made the bars semi-transparent so the colors are mixed with the background.

needs_bar_light2
needs_bar_dark2

**Comment by feelotraveller** [comment]
I like it.

Are the greens on the dark theme a bit too close?

**Comment by cvuchener** [comment]
needs_full

Unfettered color is almost cyan now, but the contrast is better. I also made the yellow a little darker.

**Pull request merged**
