### PR TITLE
32 bits compatibility, and Linux improvements

### PR DESCRIPTION
**Pull request by cvuchener**

### CODE REVIEW

**Comment by feelotraveller** [comment]
Found no problems (other than mine in getting a 32 linux df working again, fun).  No crashes when writing strings but only did basic tests.  Same compile used successfully for both architectures.

re:c705d21 .travis.yml line 38 wants off? just checking, I have no idea :)

**Comment by cvuchener** [comment]
travis compilation failed because I did too much clean up in the last patch and broke the USE_LINUX_PROCESS_VM=OFF case. I am still hesitating if I should remove it completely. I think the only linux distribution with a kernel older than 3.2 is RHEL/CentOS 6 (with linux 2.6.32). It would be very difficult to build DT with these distributions anyway because of the Qt5/C++14 requirement.

**Comment by feelotraveller** [comment]
there are a few more: [https://distrowatch.com/search.php?pkg=linux&relation=less&pkgver=3.2&distrorange=InLatest#pkgsearch](url) - and older releases as well.  but I think completely remove. 3.2 kernel itself is over 5 years old and projected EOL May '18.

**Comment by cvuchener** [comment]
Thanks for the link, but there are a lot of false positive because of missing EOL dates.

I saw references to process_vm in RHEL 6 kernel, and I wanted to check if redhat backported the API. I tried building DT on CentOS 6 (it is actually not that hard thanks to extra repos). The main problem is that I cannot run DF because of unsupported GLIBC ABI. It looks like DF 43.05 64 bits requires GLIBC_2.18 ABI, process_vm was added in glibc 2.15 according to the man page. DF 43.05 32 bits run and reading its memory with process_vm work, so it was backported (although the functions are missing from the header, I add to define them myself).

There is also Suse Linux Entreprise Desktop 11 using linux 3.0, but I cannot find if Novell is actually supporting it. [GKH declared it EOL 4 years ago](https://lkml.org/lkml/2013/10/22/125). And SLED is even worse than RHEL/CentOS regarding the glibc version (it uses 2.11).

I don't think anyone other that paid support distributions can use kernels older than 3.2. I will drop the old code using ptrace for reading/writing, I don't see the point in supporting distributions that cannot run DF.

**Pull request merged**
