### PR TITLE
Add beliefs and goals in roles

### LINKED ISSUE #87: Add beliefs and goals to roles
Split from #86.

### PR DESCRIPTION
**Pull request by cvuchener**
fix #87 

Rewrote of the custom role editor and added beliefs and goals for roles. Hopefully I did not forget any feature from the old dialog.

It is not finished yet but the core features are implemented, so it can be tested.

TODO:

 - [x] add more tooltip/statustip in the the new role editor dialog
 - [x] disable/remove items that where already added from attribute/skill/facet/belief/goal lists.
 - [x] add default global weights for beliefs and goals in "options" dialog.
 - [x] check role ratings calculation (I am not sure about the new code but I am not sure about the old one either)
 - [x] update default roles (prefs_weight was renamed preferences_weight, use of is_neg)
 - [x] use different step/range for weight double spin box for categories and aspects.
 - [x] fix bugs and add other missing features...

### CODE REVIEW

**Comment by cvuchener** [comment]
One more remark on the GUI. I left the "Category" and "Items" columns that are only used for preferences. I think that they could be removed and the information could be moved to a tooltip or statustip.

---

There are some compilation issues with travis or msvc2015.

Missing includes:
 - #include <QStatusTipEvent> in roledialog.cpp
 - #include <functional> in rolemodel.cpp

MSVC2015 requires RoleModel::AspectInfo to be public.

**Comment by cvuchener** [comment]
new version:
 - fixed compilation (hopefully)
 - fixed some confusion between category weights and aspect weights
 - added a few tool tips and status tips for the role view (status tips are not working consistently)

**Comment by cvuchener** [comment]
new version
 - fix unused variables
 - fix status tips in aspect tree view (added mouse tracking)
 - change spinbox minium value to 0 for category weights
 - hide attributes/skills/facets/beliefs/goals when already added (not for preferences)

**Comment by cvuchener** [comment]
- Rebased on PR #101 
 - Added diagnostics for new role updates (preference_weigt and is_neg) and updated default roles.
 - new commit for optional overwritten default weights.

At this point, I think it is almost ready, I would like some testing and feedback.

**Comment by cvuchener** [comment]
Rebased on v40.1.0 and added optional collapse/expand button in SearchFilterTreeView.

**Comment by cvuchener** [comment]
>  For the items within each group (e.g. Creativity) there was nothing I could figure out to alter the weight, no right click, no spinner. 

Quick patch for weight editors to open more easily (maybe too easily). @feelotraveller apply this with `git apply` from project root or `src` dir.

```diff
diff --git a/src/roledialog.cpp b/src/roledialog.cpp
index 1bd0c95..97a79b0 100644
--- a/src/roledialog.cpp
+++ b/src/roledialog.cpp
@@ -115,6 +115,7 @@ RoleDialog::RoleDialog(RolePreferenceModel *pref_model, QWidget *parent)
 
     // Setup aspects tree view
     ui->tree_aspects->setItemDelegateForColumn(RoleModel::ColumnWeight, &m_weight_delegate);
+    ui->tree_aspects->setEditTriggers(QAbstractItemView::AllEditTriggers);
     ui->tree_aspects->setModel(m_model.get());
 
     connect(ui->tree_aspects, &QWidget::customContextMenuRequested,
diff --git a/src/rolemodel.cpp b/src/rolemodel.cpp
index 973f27a..7ad3ce6 100644
--- a/src/rolemodel.cpp
+++ b/src/rolemodel.cpp
@@ -302,7 +302,7 @@ QVariant RoleModel::data(const QModelIndex &index, int role) const
                     ? tr("default (%1)").arg(QString::number(value))
                     : QString::number(value);
             case Qt::EditRole:
-                return (double) value;
+                return w.is_default ? 0.0 : value;
             case Qt::ToolTipRole:
                 return tr("%1 weight").arg(info->category_name);
             case Qt::StatusTipRole:
```

Or to be a little less aggressive, replace `QAbstractItemView::AllEditTriggers` with `QAbstractItemView::DoubleClicked|QAbstractItemView::SelectedClicked|QAbstractItemView::EditKeyPressed|QAbstractItemView::AnyKeyPressed` (for the curious the reference for these flags is [here](https://doc.qt.io/qt-5/qabstractitemview.html#EditTrigger-enum)).

**Comment by feelotraveller** [comment]
Just saw the patch.  I will give some feedback but it will be tomorrow now.

Different issue - roles calculation.  I noticed it with a custom role and I think it reveals a problem with the new calculation.  Orderly role: attributes - strength, agility, empathy (all at weight 1) - facets - altruism weight 1.  Comparison uses the default defaults for the groups.  Up to and including 40.1.2 this role has returned seemingly reasonable ratings, For my current starting 7 40.1.2 returns 30, 37, 50, 53, 54, 54, 54.  However with the new calculations the same 7 return 1, 2, 6, 8, 9, 9, 9.  These latter seem quite off as the dwarfs are not particularly remarkable in their attributes and altruism and should be somewhere around middling for the role.

**Comment by cvuchener** [comment]
Thanks, I see it. There is an issue with skill and preference normalization. A negative infinity has been added in the data (I don't know from why yet), making all skill and preference ratings very high thus roles without them have low ratings by comparison.

Looking at this, I saw another issue with roles as they are computed. Currently if a category is empty, a 50% rating is used. This make roles with less categories (e.g. only attributes or only skills) less extreme than roles with more categories (e.g. attributes + skills + preferences). Another solution could be to set the weight for empty categories to 0. But I won't do that change in this pull request.

**Comment by cvuchener** [comment]
- Rebased on v40.1.2
 - fix rolestas params
 - fix using global default
 - added any key edit trigger for weight (let you type the weight when the cell is selected)

Now the raw role ratings are the same as v40.1.2 if I set beliefs and goals weight to zero. But normalized role ratings are different (same issue as #55?).

Currently zero weight is used in the dialog to use the global default weight. Maybe I should allow to set the weight to zero. However, this would prevent resetting to default from the spinbox, only the context menu would be able to do so.

**Comment by feelotraveller** [comment]
Almost cross-posted.  Thanks. After applying the patch it works well for me (=I like the single click behaviour).

I would have to look more closely at the role ratings (both with big and small sets of dwarfs) to give better feedback on that.  Setting the weight to zero for empty categories seems like a better interim solution than considering them as 50%.  (There is however the consideration that depending on the number of active categories items that match will have different degrees of influence.)

Would it be possible to use negative weight to set the global default weight?  I think the only place a negative weight is currently used in the roles is for the engraver role but that is actually redundant since every dwarf hates one vermin or another.

**Comment by cvuchener** [comment]
New changes
 - Qt model have this "buddy" system that let you redirect the edition to another item. So now double clicking or pressing a key while anywhere on the line, will edit the weight.
 - I added an action in the context menu for editing the weight, it also works anywhere on the line.

Regarding edit triggers, I find `CurrentChanged` annoying. `SelectedClicked` is not reactive since it waits to see if it is single or double click, I am not convinced it is useful. I like `AnyKeyPressed` as it lets you directly type a number when the editor is not shown yet.

Negative weight is only used for individual aspect, not global category weights. The spinbox has its minimum set to 0, and I'd like to keep it that way.

Settings the global defaults to 0 for beliefs and goals may make this changes less intrusive. But users who want to try the new features may forget to set a proper weight. I am divided there.

**Comment by feelotraveller** [comment]
1) The double-click behaviour with the buddy system is probably better.  While I liked the single-click I can see it annoying some people.  I don't mind if the context menu change stays or goes.

2) Currently I would support setting non-zero default weights for beliefs and goals since they are effectively zero with the current build anyway since all the roles lack relevant specifications.  I incidentally tested a belief (knowledge for scholars) and at first glance had no problem with the effect using the global default.

3) Just to continue the comparsion feedback with the same starting 7 (still yet to be unpaused...) my Orderly role now ranks 20, 26, 53, 66, 69, 70, 71.  Not sure what I think about the new distribution yet but this is in line with the other roles.

4) On that regard, at first inspection I wonder if the preferences are currently too highly weighted.  I also wonder if the distribution needs to be shaped so that there are more results closer to the 50 mark.  Passing comments, I will want to observe more before firming these up or retracting them.

5) I did experience a (non-reproducible) crash at one stage, and a lock-up at another.  The crash was after opening the 'edit custom role' when selecting the role to edit, unless I misclicked but I don't think so.  There was nothing in the terminal log (not running debug mode) but I did notice that I had just made a read.  I tried unsuccessfully to reproduce the behaviour.  The lock-up occurred when initially opening the application without internet access (automatic checks turned off) and quickly clicking the 'connect' button.  I did not attempt to reproduce. The common factor was perhaps doing operations quickly?  (Again these are comments in passing rather than anything major for me.)

6) Finally, off on a tangent, I did a bit of investigation and the preference, weighted at -1, for hateable creatures does not register in the roles calculation. This is used only by the Engraver role. The (rare) matches for liking hateable creatures (all dwarfs hate one) are shown graphically on the grid view and listed in the tooltip but deleting either the liked hateable creature preference, or the hated hateable creature preference makes no impact on the roles calculation.  [The intent was to make those dwarfs who also have a positive preference (they always have a negative preference) not rank as highly in suitability for the role.  Dwarfs frequently engrave creatures they are positively or negatively inclined towards.]

**Comment by cvuchener** [comment]
> Currently I would support setting non-zero default weights for beliefs and goals since they are effectively zero with the current build anyway since all the roles lack relevant specifications. I incidentally tested a belief (knowledge for scholars) and at first glance had no problem with the effect using the global default.

It should affect all roles equally. Order should stay the same. And the normalization should keep the ratings nicely spread.

I will keep testing with zero weight for now, it is a good way to check I did not change the role computation (this PR is about refactoring, new role editor, and belief and goal addition). Computation may need to be changed later (normalization algorithm and preference raw ratings need improvements), but I am trying to keep the same roles for now.

> On that regard, at first inspection I wonder if the preferences are currently too highly weighted. I also wonder if the distribution needs to be shaped so that there are more results closer to the 50 mark. Passing comments, I will want to observe more before firming these up or retracting them.

Preference rating computation is weird currently. But I think the extreme ratings mostly come from the normalization. When I checked rating details, one matched preference would make a 70% rating when most other ratings were much closer to 50%.

Goals will have the same issue, they are 0% or 100%, no middle value. Actually goals should have a even lower weight than preferences, now that I think about that. They have extreme ratings while being less influential.

> I did experience a (non-reproducible) crash at one stage, and a lock-up at another. The crash was after opening the 'edit custom role' when selecting the role to edit, unless I misclicked but I don't think so. There was nothing in the terminal log (not running debug mode) but I did notice that I had just made a read. I tried unsuccessfully to reproduce the behaviour.

If you use debug builds, crashes may dump cores depending on your system configuration. Cores can be used later to debug with gdb.

> The lock-up occurred when initially opening the application without internet access (automatic checks turned off) and quickly clicking the 'connect' button. I did not attempt to reproduce. The common factor was perhaps doing operations quickly? (Again these are comments in passing rather than anything major for me.)

Do you use "Read on Startup"? If yes, you should not need to click "Connect". I tried clicking it during automatic connection on v40.1.2 (not this branch) and it crashed. This button is not disabled soon enough, but this not part of this PR.

**Comment by cvuchener** [comment]
I did not copy a parameter correctly, I fixed it. I now get the exact same role ratings than the master (v40.1.2) version.

**Pull request merged**
