### PR TITLE
Memory layouts for 0.44.11

### PR DESCRIPTION
**Pull request by cvuchener**

### CODE REVIEW

**Comment by tschoppi** [comment]
For me something is not working. I built manually from the branch (Arch Linux, but `setcap` with the corresponding attributes has been done on the binary) but get a weird error:

```
2018-Jun-26 16:48:52.368 INFO	core	Dwarf fortress path: "/home/tschoppi/.dwarffortress" [/home/tschoppi/projects/cvuchenerDT/src/dfinstancelinux.cpp:262] (find_running_copy)
2018-Jun-26 16:48:52.405 INFO	core	Setting memory layout for DF checksum "0xe05a549a" [/home/tschoppi/projects/cvuchenerDT/src/dfinstance.cpp:1086] (set_memory_layout)
2018-Jun-26 16:48:52.405 INFO	core	Detected Dwarf Fortress version "v0.44.11 linux64" using MemoryLayout from "/home/tschoppi/.local/share/dwarftherapist/memory_layouts/linux/v0.44.11_linux64.ini" [/home/tschoppi/projects/cvuchenerDT/src/dfinstance.cpp:1091] (set_memory_layout)
2018-Jun-26 16:48:52.405 INFO	core	Connection to DF version "v0.44.11 linux64" established. [/home/tschoppi/projects/cvuchenerDT/src/mainwindow.cpp:432] (connect_to_df)
2018-Jun-26 16:48:52.406 ERROR	core	READ_RAW: "Bad address" READING 24 BYTES FROM "0x41495245fffeffe8" TO 0x55bb88f5b430 [/home/tschoppi/projects/cvuchenerDT/src/dfinstancelinux.cpp:115] (read_raw)
2018-Jun-26 16:48:52.406 ERROR	core	Invalid string at "0x00007f8660ac2a70" [/home/tschoppi/projects/cvuchenerDT/src/dfinstancelinux.cpp:397] (read_string)
2018-Jun-26 16:48:52.406 ERROR	core	Invalid string at "0x00007f8660ac2a78" [/home/tschoppi/projects/cvuchenerDT/src/dfinstancelinux.cpp:397] (read_string)
```

Maybe this is total user error, first time compiliing and using it myself, but I wanted to note it in the PR just to be safe.

**Comment by cvuchener** [comment]
I recently updated this branch. Are you sure you have the latest version (check the commit hash)? You may need to use `git pull --force` since I edited existing commits.

Add option `--debug` when running DT, if the error happens when reading languages, this is the bug from the first version of the memory layouts.

> Arch Linux, but setcap with the corresponding attributes has been done on the binary

I don't remember Arch having ptrace_scope enabled by default. If it is enabled and you value security, you may prefer trying [one of this method](http://www.bay12forums.com/smf/index.php?topic=168411.msg7742913#msg7742913) (the second is simpler).

**Comment by feelotraveller** [comment]
https://wiki.archlinux.org/index.php/Security#ptrace_scope
"Arch enables the Yama LSM by default, providing a kernel.yama.ptrace_scope flag. This flag is enabled by default and prevents processes from performing a ptrace call on other processes outside of their scope without CAP_SYS_PTRACE."

On Archlinux based Manjaro the following works for me to permanently set for a build.
>sudo setcap cap_sys_ptrace=ep /path/to/DwarfTherapist

But I suspect you are right in thinking it was the earlier version of the memory layouts causing the problem. :smile_cat:

**Comment by tschoppi** [comment]
I didn't realize that there were any updates to the memory layout. Updating the branch (had to delete the local branch and check it out again from the remote branch) did the trick.

Thanks for the good work! :+1:

**Comment by tschoppi** [comment]
Re cap_sys_ptrace: The AUR package automatically sets the flag, so I really don't mind it. Just figured I'd mention it since that seemed to be a likely source of user error. (And I couldn't wait until the PR got merged, after 2 migration waves managing dorfs via the in-game interface becomes too cumbersome.)

**Comment by feelotraveller** [comment]
@cvuchener
fyi (just in case) packages have been maintained for several years in the Arch User Repository
https://aur.archlinux.org/packages/?O=0&K=therapist
they switched to this fork about 6 months back :smiley:

**Comment by cvuchener** [comment]
updated "extracts" offset.

**Pull request merged**
