### PR TITLE
Add memory layouts for 0.47.03

### PR DESCRIPTION
**Pull request by cvuchener**

### CODE REVIEW

**Comment by croftp2** [comment]
I'd like to test these changes but when I pulled this command and upped the LNP manifest, 47.03 still wasn't listed as a compatible version. Is that a bug or am I missing something? Thanks in advance

**Comment by cvuchener** [comment]
What do you mean "not listed"? The only list I know is in the log. If the memory layout is missing there, you either put it in the wrong location, or the file doesn't have a ".ini" extension.

The LNP manifest is only used by PyLNP, not by DT. Its content or its absence won't prevent DT from working.

**Comment by lethosor** [comment]
Can you clarify what you mean by "pulled this command"?
All you should need to do is drop the appropriate .ini file from here into an existing DT installation.

**Comment by croftp2** [comment]
Sorry, I wrote "command" but meant "commit". I'm on x64 Ubuntu 18.04.  
I put the 47.03 memory layout .ini files in `Dwarf-Therapist/share/memory_layouts/linux/`
ran the usual 
```mkdir Dwarf-Therapist/build4703 && cd Dwarf-Therapist/build4703 && cmake .. && make```
However after loading a 47.03 fortress and running `Dwarf-Therapist/build4703/dwarftherapist` I get this error
dfdt_error

**Comment by lethosor** [comment]
I can't see the full list of supported versions in your screenshot - does the list include "v0.47.03 linux64" (or any 0.47.03)?
The layout path might be relative to the DT binary - @cvuchener would know better than I if you've put them in the right spot.

**Comment by croftp2** [comment]
Yeah I wasn't able to expand the window enough to include all the versions but 0.47.03 is not in the list. v0.47.02 linux64 and all of the other versions in share/memory_layouts/linux are in this list though. That's what I'm having trouble with. I have put these new layouts in the same directory as the other layouts but maybe DT isn't recognizing them?

**Comment by croftp2** [comment]
After taking a look at the logs, I realized I was putting the layouts in the wrong locations. It looks like when this commit goes through, DT will be able to download the new layouts and place them in `/usr/share/dwarftherapist/` instead. I tried putting the new layouts here instead and was able to connect and manage the dwarves. Thanks @lethosor and @cvuchener
dt_success

**Comment by cvuchener** [comment]
> The layout path might be relative to the DT binary - @cvuchener would know better than I if you've put them in the right spot.

Not in normal mode on Linux. The path are `$XDG_DATA_DIRS/dwarftherapist/memory_layouts/linux`, if you did not touch the [XDG environment variables](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), that's usually:

 - `~/.local/share/dwarftherapist/memory_layouts/linux`
 - `/usr/local/share/dwarftherapist/memory_layouts/linux`
 - `/usr/share/dwarftherapist/memory_layouts/linux`

There are also portable mode using `../share/memory_layouts/linux` relative to the binary and developer mode looking both `share` next to the binary and the `memory_layouts` directory from the source directory.

You can use *File* → *Open data directory* on all platforms if you are unsure.

**Comment by kiswa** [comment]
Does this have a scheduled release date?

**Comment by cvuchener** [comment]
Right before DF 0.47.04 release, probably.

**Comment by shaggyfrog** [comment]
If someone can give me a quick explanation for how to create the memory layouts for macOS, I'd be happy to lend a hand.

**Comment by clinodev** [comment]
Are the 47.03 experimental layouts not working for MacOS? I hadn't seen reports on reddit.

http://www.bay12forums.com/smf/index.php?topic=168411.msg8092372#msg8092372

**Comment by shaggyfrog** [comment]
> Are the 47.03 experimental layouts not working for MacOS? I hadn't seen reports on reddit.
> 
> http://www.bay12forums.com/smf/index.php?topic=168411.msg8092372#msg8092372

Stupid me, I didn't see them in the commits until now!

**Pull request merged**
